;
; $xx00 relocatable library
;

%memtop $FFFF
%address $1000
%output library
%zeropage dontuse

%import textio

main {
    ; this must be first in main!
    %asm {{
        ; the first entry for start is always generated by the compiler
        ; adding here commented out for reference
        ;jmp p8b_main.p8s_start
        jmp p8b_main.p8s_link
        jmp p8b_main.p8s_myprint
        jmp p8b_main.p8s_myprint_ub
        jmp p8b_main.p8s_myprint_uw
    }}

    sub start() {
        txt.print("test.lib start() called...\n")
    }

    ; copy link table from main prg
    sub link() {
        txt.print("hello from test.lib link()...\n")
    }

    ; just call print included in the lib
    sub myprint(str text) {
        txt.print(text)
    }

    ; just call print_ub included in the lib
    sub myprint_ub(ubyte value) {
        txt.print_ub(value)
    }

    ; just call print_uw included in the lib
    sub myprint_uw(uword value) {
        txt.print_uw(value)
    }
}
